typedef struct {
    float r, i;
} floatc_t;
typedef struct {
    double r, i;
} doublec_t;
void srotg_(float *, float *, float *, float *);
void drotg_(double *, double *, double *, double *);
void srotmg_(float *, float *, float *, float *, float *);
void drotmg_(double *, double *, double *, double *, double *);
void srot_(int *, float *, int *, float *, int *, float *, float *);
void drot_(int *, double *, int *, double *, int *, double *, double *);
void srotm_(int *, float *, int *, float *, int *, float *);
void drotm_(int *, double *, int *, double *, int *, double *);
void sswap_(int *, float *, int *, float *, int *);
void dswap_(int *, double *, int *, double *, int *);
void cswap_(int *, float *, int *, float *, int *);
void zswap_(int *, double *, int *, double *, int *);
void sscal_(int *, float *, float *, int *);
void dscal_(int *, double *, double *, int *);
void cscal_(int *, float *, float *, int *);
void zscal_(int *, double *, double *, int *);
void csscal_(int *, float *, float *, int *);
void zdscal_(int *, double *, double *, int *);
void scopy_(int *, float *, int *, float *, int *);
void dcopy_(int *, double *, int *, double *, int *);
void ccopy_(int *, float *, int *, float *, int *);
void zcopy_(int *, double *, int *, double *, int *);
void saxpy_(int *, float *, float *, int *, float *, int *);
void daxpy_(int *, double *, double *, int *, double *, int *);
void caxpy_(int *, float *, float *, int *, float *, int *);
void zaxpy_(int *, double *, double *, int *, double *, int *);
float sdot_(int *, float *, int *, float *, int *);
double ddot_(int *, double *, int *, double *, int *);
double dsdot_(int *, float *, int *, float *, int *);
floatc_t cdotu_(int *, float *, int *, float *, int *);
doublec_t zdotu_(int *, double *, int *, double *, int *);
floatc_t cdotc_(int *, float *, int *, float *, int *);
doublec_t zdotc_(int *, double *, int *, double *, int *);
float sdsdot_(int *, float *, float *, int *, float *, int *);
float snrm2_(int *, float *, int *);
double dnrm2_(int *, double *, int *);
float scnrm2_(int *, float *, int *);
double dznrm2_(int *, double *, int *);
float sasum_(int *, float *, int *);
double dasum_(int *, double *, int *);
float scasum_(int *, float *, int *);
double dzasum_(int *, double *, int *);
int isamax_(int *, float *, int *);
int idamax_(int *, double *, int *);
int icamax_(int *, float *, int *);
int izamax_(int *, double *, int *);
void sgemv_(char *, int *, int *, float *, float *, int *, float *, int *, float *, float *, int *);
void dgemv_(char *, int *, int *, double *, double *, int *, double *, int *, double *, double *, int *);
void cgemv_(char *, int *, int *, float *, float *, int *, float *, int *, float *, float *, int *);
void zgemv_(char *, int *, int *, double *, double *, int *, double *, int *, double *, double *, int *);
void sgbmv_(char *, int *, int *, int *, int *, float *, float *, int *, float *, int *, float *, float *, int *);
void dgbmv_(char *, int *, int *, int *, int *, double *, double *, int *, double *, int *, double *, double *, int *);
void cgbmv_(char *, int *, int *, int *, int *, float *, float *, int *, float *, int *, float *, float *, int *);
void zgbmv_(char *, int *, int *, int *, int *, double *, double *, int *, double *, int *, double *, double *, int *);
void chemv_(char *, int *, float *, float *, int *, float *, int *, float *, float *, int *);
void zhemv_(char *, int *, double *, double *, int *, double *, int *, double *, double *, int *);
void chbmv_(char *, int *, int *, float *, float *, int *, float *, int *, float *, float *, int *);
void zhbmv_(char *, int *, int *, double *, double *, int *, double *, int *, double *, double *, int *);
void chpmv_(char *, int *, float *, float *, float *, int *, float *, float *, int *);
void zhpmv_(char *, int *, double *, double *, double *, int *, double *, double *, int *);
void ssymv_(char *, int *, float *, float *, int *, float *, int *, float *, float *, int *);
void dsymv_(char *, int *, double *, double *, int *, double *, int *, double *, double *, int *);
void ssbmv_(char *, int *, int *, float *, float *, int *, float *, int *, float *, float *, int *);
void dsbmv_(char *, int *, int *, double *, double *, int *, double *, int *, double *, double *, int *);
void sspmv_(char *, int *, float *, float *, float *, int *, float *, float *, int *);
void dspmv_(char *, int *, double *, double *, double *, int *, double *, double *, int *);
void strmv_(char *, char *, char *, int *, float *, int *, float *, int *);
void dtrmv_(char *, char *, char *, int *, double *, int *, double *, int *);
void ctrmv_(char *, char *, char *, int *, float *, int *, float *, int *);
void ztrmv_(char *, char *, char *, int *, double *, int *, double *, int *);
void stbmv_(char *, char *, char *, int *, int *, float *, int *, float *, int *);
void dtbmv_(char *, char *, char *, int *, int *, double *, int *, double *, int *);
void ctbmv_(char *, char *, char *, int *, int *, float *, int *, float *, int *);
void ztbmv_(char *, char *, char *, int *, int *, double *, int *, double *, int *);
void stpmv_(char *, char *, char *, int *, float *, float *, int *);
void dtpmv_(char *, char *, char *, int *, double *, double *, int *);
void ctpmv_(char *, char *, char *, int *, float *, float *, int *);
void ztpmv_(char *, char *, char *, int *, double *, double *, int *);
void strsv_(char *, char *, char *, int *, float *, int *, float *, int *);
void dtrsv_(char *, char *, char *, int *, double *, int *, double *, int *);
void ctrsv_(char *, char *, char *, int *, float *, int *, float *, int *);
void ztrsv_(char *, char *, char *, int *, double *, int *, double *, int *);
void stbsv_(char *, char *, char *, int *, int *, float *, int *, float *, int *);
void dtbsv_(char *, char *, char *, int *, int *, double *, int *, double *, int *);
void ctbsv_(char *, char *, char *, int *, int *, float *, int *, float *, int *);
void ztbsv_(char *, char *, char *, int *, int *, double *, int *, double *, int *);
void stpsv_(char *, char *, char *, int *, float *, float *, int *);
void dtpsv_(char *, char *, char *, int *, double *, double *, int *);
void ctpsv_(char *, char *, char *, int *, float *, float *, int *);
void ztpsv_(char *, char *, char *, int *, double *, double *, int *);
void sger_(int *, int *, float *, float *, int *, float *, int *, float *, int *);
void dger_(int *, int *, double *, double *, int *, double *, int *, double *, int *);
void cgeru_(int *, int *, float *, float *, int *, float *, int *, float *, int *);
void zgeru_(int *, int *, double *, double *, int *, double *, int *, double *, int *);
void cgerc_(int *, int *, float *, float *, int *, float *, int *, float *, int *);
void zgerc_(int *, int *, double *, double *, int *, double *, int *, double *, int *);
void cher_(char *, int *, float *, float *, int *, float *, int *);
void zher_(char *, int *, double *, double *, int *, double *, int *);
void chpr_(char *, int *, float *, float *, int *, float *);
void zhpr_(char *, int *, double *, double *, int *, double *);
void cher2_(char *, int *, float *, float *, int *, float *, int *, float *, int *);
void zher2_(char *, int *, double *, double *, int *, double *, int *, double *, int *);
void chpr2_(char *, int *, float *, float *, int *, float *, int *, float *);
void zhpr2_(char *, int *, double *, double *, int *, double *, int *, double *);
void ssyr_(char *, int *, float *, float *, int *, float *, int *);
void dsyr_(char *, int *, double *, double *, int *, double *, int *);
void sspr_(char *, int *, float *, float *, int *, float *);
void dspr_(char *, int *, double *, double *, int *, double *);
void ssyr2_(char *, int *, float *, float *, int *, float *, int *, float *, int *);
void dsyr2_(char *, int *, double *, double *, int *, double *, int *, double *, int *);
void sspr2_(char *, int *, float *, float *, int *, float *, int *, float *);
void dspr2_(char *, int *, double *, double *, int *, double *, int *, double *);
void sgemm_(char *, char *, int *, int *, int *, float *, float *, int *, float *, int *, float *, float *, int *);
void dgemm_(char *, char *, int *, int *, int *, double *, double *, int *, double *, int *, double *, double *, int *);
void cgemm_(char *, char *, int *, int *, int *, float *, float *, int *, float *, int *, float *, float *, int *);
void zgemm_(char *, char *, int *, int *, int *, double *, double *, int *, double *, int *, double *, double *, int *);
void ssymm_(char *, char *, int *, int *, float *, float *, int *, float *, int *, float *, float *, int *);
void dsymm_(char *, char *, int *, int *, double *, double *, int *, double *, int *, double *, double *, int *);
void csymm_(char *, char *, int *, int *, float *, float *, int *, float *, int *, float *, float *, int *);
void zsymm_(char *, char *, int *, int *, double *, double *, int *, double *, int *, double *, double *, int *);
void chemm_(char *, char *, int *, int *, float *, float *, int *, float *, int *, float *, float *, int *);
void zhemm_(char *, char *, int *, int *, double *, double *, int *, double *, int *, double *, double *, int *);
void ssyrk_(char *, char *, int *, int *, float *, float *, int *, float *, float *, int *);
void dsyrk_(char *, char *, int *, int *, double *, double *, int *, double *, double *, int *);
void csyrk_(char *, char *, int *, int *, float *, float *, int *, float *, float *, int *);
void zsyrk_(char *, char *, int *, int *, double *, double *, int *, double *, double *, int *);
void cherk_(char *, char *, int *, int *, float *, float *, int *, float *, float *, int *);
void zherk_(char *, char *, int *, int *, double *, double *, int *, double *, double *, int *);
void ssyr2k_(char *, char *, int *, int *, float *, float *, int *, float *, int *, float *, float *, int *);
void dsyr2k_(char *, char *, int *, int *, double *, double *, int *, double *, int *, double *, double *, int *);
void csyr2k_(char *, char *, int *, int *, float *, float *, int *, float *, int *, float *, float *, int *);
void zsyr2k_(char *, char *, int *, int *, double *, double *, int *, double *, int *, double *, double *, int *);
void cher2k_(char *, char *, int *, int *, float *, float *, int *, float *, int *, float *, float *, int *);
void zher2k_(char *, char *, int *, int *, double *, double *, int *, double *, int *, double *, double *, int *);
void strmm_(char *, char *, char *, char *, int *, int *, float *, float *, int *, float *, int *);
void dtrmm_(char *, char *, char *, char *, int *, int *, double *, double *, int *, double *, int *);
void ctrmm_(char *, char *, char *, char *, int *, int *, float *, float *, int *, float *, int *);
void ztrmm_(char *, char *, char *, char *, int *, int *, double *, double *, int *, double *, int *);
void strsm_(char *, char *, char *, char *, int *, int *, float *, float *, int *, float *, int *);
void dtrsm_(char *, char *, char *, char *, int *, int *, double *, double *, int *, double *, int *);
void ctrsm_(char *, char *, char *, char *, int *, int *, float *, float *, int *, float *, int *);
void ztrsm_(char *, char *, char *, char *, int *, int *, double *, double *, int *, double *, int *);
