#ifndef BLAS_H
#define BLAS_H
typedef struct {
    float r, i;
} floatc_t;
typedef struct {
    double r, i;
} doublec_t;
void caxpy(const int *, const float *, const float *, const int *, float *, const int *);
void ccopy(const int *, const float *, const int *, float *, const int *);
floatc_t cdotc(float *, const int *, const float *, const int *, const float *, const int *);
floatc_t cdotu(float *, const int *, const float *, const int *, const float *, const int *);
void cgbmv(const char *, const int *, const int *, const int *, const int *, const float *, const float *, const int *, const float *, const int *, const float *, float *, const int *);
void cgemm(const char *, const char *, const int *, const int *, const int *, const float *, const float *, const int *, const float *, const int *, const float *, float *, const int *);
void cgemv(const char *, const int *, const int *, const float *, const float *, const int *, const float *, const int *, const float *, float *, const int *);
void cgerc(const int *, const int *, const float *, const float *, const int *, const float *, const int *, float *, const int *);
void cgeru(const int *, const int *, const float *, const float *, const int *, const float *, const int *, float *, const int *);
void chbmv(const char *, const int *, const int *, const float *, const float *, const int *, const float *, const int *, const float *, float *, const int *);
void chemm(const char *, const char *, const int *, const int *, const float *, const float *, const int *, const float *, const int *, const float *, float *, const int *);
void chemv(const char *, const int *, const float *, const float *, const int *, const float *, const int *, const float *, float *, const int *);
void cher(const char *, const int *, const float *, const float *, const int *, float *, const int *);
void cher2(const char *, const int *, const float *, const float *, const int *, const float *, const int *, float *, const int *);
void cher2k(const char *, const char *, const int *, const int *, const float *, const float *, const int *, const float *, const int *, const float *, float *, const int *);
void cherk(const char *, const char *, const int *, const int *, const float *, const float *, const int *, const float *, float *, const int *);
void chpmv(const char *, const int *, const float *, const float *, const float *, const int *, const float *, float *, const int *);
void chpr(const char *, const int *, const float *, const float *, const int *, float *);
void chpr2(const char *, const int *, const float *, const float *, const int *, const float *, const int *, float *);
void cscal(const int *, const float *, float *, const int *);
void csscal(const int *, const float *, float *, const int *);
void cswap(const int *, float *, const int *, float *, const int *);
void csymm(const char *, const char *, const int *, const int *, const float *, const float *, const int *, const float *, const int *, const float *, float *, const int *);
void csyr2k(const char *, const char *, const int *, const int *, const float *, const float *, const int *, const float *, const int *, const float *, float *, const int *);
void csyrk(const char *, const char *, const int *, const int *, const float *, const float *, const int *, const float *, float *, const int *);
void ctbmv(const char *, const char *, const char *, const int *, const int *, const float *, const int *, float *, const int *);
void ctbsv(const char *, const char *, const char *, const int *, const int *, const float *, const int *, float *, const int *);
void ctpmv(const char *, const char *, const char *, const int *, const float *, float *, const int *);
void ctpsv(const char *, const char *, const char *, const int *, const float *, float *, const int *);
void ctrmm(const char *, const char *, const char *, const char *, const int *, const int *, const float *, const float *, const int *, float *, const int *);
void ctrmv(const char *, const char *, const char *, const int *, const float *, const int *, float *, const int *);
void ctrsm(const char *, const char *, const char *, const char *, const int *, const int *, const float *, const float *, const int *, float *, const int *);
void ctrsv(const char *, const char *, const char *, const int *, const float *, const int *, float *, const int *);
double dasum(const int *, const double *, const int *);
void daxpy(const int *, const double *, const double *, const int *, double *, const int *);
void dcopy(const int *, const double *, const int *, double *, const int *);
double ddot(const int *, const double *, const int *, const double *, const int *);
void dgbmv(const char *, const int *, const int *, const int *, const int *, const double *, const double *, const int *, const double *, const int *, const double *, double *, const int *);
void dgemm(const char *, const char *, const int *, const int *, const int *, const double *, const double *, const int *, const double *, const int *, const double *, double *, const int *);
void dgemv(const char *, const int *, const int *, const double *, const double *, const int *, const double *, const int *, const double *, double *, const int *);
void dger(const int *, const int *, const double *, const double *, const int *, const double *, const int *, double *, const int *);
double dnrm2(const int *, const double *, const int *);
void drot(const int *, double *, const int *, double *, const int *, const double *, const double *);
void drotg(double *, double *, double *, double *);
void drotm(const int *, double *, const int *, double *, const int *, const double *);
void drotmg(double *, double *, double *, const double *, double *);
void dsbmv(const char *, const int *, const int *, const double *, const double *, const int *, const double *, const int *, const double *, double *, const int *);
void dscal(const int *, const double *, double *, const int *);
double dsdot(const int *, const float *, const int *, const float *, const int *);
void dspmv(const char *, const int *, const double *, const double *, const double *, const int *, const double *, double *, const int *);
void dspr(const char *, const int *, const double *, const double *, const int *, double *);
void dspr2(const char *, const int *, const double *, const double *, const int *, const double *, const int *, double *);
void dswap(const int *, double *, const int *, double *, const int *);
void dsymm(const char *, const char *, const int *, const int *, const double *, const double *, const int *, const double *, const int *, const double *, double *, const int *);
void dsymv(const char *, const int *, const double *, const double *, const int *, const double *, const int *, const double *, double *, const int *);
void dsyr(const char *, const int *, const double *, const double *, const int *, double *, const int *);
void dsyr2(const char *, const int *, const double *, const double *, const int *, const double *, const int *, double *, const int *);
void dsyr2k(const char *, const char *, const int *, const int *, const double *, const double *, const int *, const double *, const int *, const double *, double *, const int *);
void dsyrk(const char *, const char *, const int *, const int *, const double *, const double *, const int *, const double *, double *, const int *);
void dtbmv(const char *, const char *, const char *, const int *, const int *, const double *, const int *, double *, const int *);
void dtbsv(const char *, const char *, const char *, const int *, const int *, const double *, const int *, double *, const int *);
void dtpmv(const char *, const char *, const char *, const int *, const double *, double *, const int *);
void dtpsv(const char *, const char *, const char *, const int *, const double *, double *, const int *);
void dtrmm(const char *, const char *, const char *, const char *, const int *, const int *, const double *, const double *, const int *, double *, const int *);
void dtrmv(const char *, const char *, const char *, const int *, const double *, const int *, double *, const int *);
void dtrsm(const char *, const char *, const char *, const char *, const int *, const int *, const double *, const double *, const int *, double *, const int *);
void dtrsv(const char *, const char *, const char *, const int *, const double *, const int *, double *, const int *);
double dzasum(const int *, const double *, const int *);
double dznrm2(const int *, const double *, const int *);
int icamax(const int *, const float *, const int *);
int idamax(const int *, const double *, const int *);
int isamax(const int *, const float *, const int *);
int izamax(const int *, const double *, const int *);
float sasum(const int *, const float *, const int *);
void saxpy(const int *, const float *, const float *, const int *, float *, const int *);
float scasum(const int *, const float *, const int *);
float scnrm2(const int *, const float *, const int *);
void scopy(const int *, const float *, const int *, float *, const int *);
float sdot(const int *, const float *, const int *, const float *, const int *);
float sdsdot(const int *, const float *, const float *, const int *, const float *, const int *);
void sgbmv(const char *, const int *, const int *, const int *, const int *, const float *, const float *, const int *, const float *, const int *, const float *, float *, const int *);
void sgemm(const char *, const char *, const int *, const int *, const int *, const float *, const float *, const int *, const float *, const int *, const float *, float *, const int *);
void sgemv(const char *, const int *, const int *, const float *, const float *, const int *, const float *, const int *, const float *, float *, const int *);
void sger(const int *, const int *, const float *, const float *, const int *, const float *, const int *, float *, const int *);
float snrm2(const int *, const float *, const int *);
void srot(const int *, float *, const int *, float *, const int *, const float *, const float *);
void srotg(float *,float *,float *,float *);
void srotm(const int *, float *, const int *, float *, const int *, const float *);
void srotmg(float *, float *, float *, const float *, float *);
void ssbmv(const char *, const int *, const int *, const float *, const float *, const int *, const float *, const int *, const float *, float *, const int *);
void sscal(const int *, const float *, float *, const int *);
void sspmv(const char *, const int *, const float *, const float *, const float *, const int *, const float *, float *, const int *);
void sspr(const char *, const int *, const float *, const float *, const int *, float *);
void sspr2(const char *, const int *, const float *, const float *, const int *, const float *, const int *, float *);
void sswap(const int *, float *, const int *, float *, const int *);
void ssymm(const char *, const char *, const int *, const int *, const float *, const float *, const int *, const float *, const int *, const float *, float *, const int *);
void ssymv(const char *, const int *, const float *, const float *, const int *, const float *, const int *, const float *, float *, const int *);
void ssyr(const char *, const int *, const float *, const float *, const int *, float *, const int *);
void ssyr2(const char *, const int *, const float *, const float *, const int *, const float *, const int *, float *, const int *);
void ssyr2k(const char *, const char *, const int *, const int *, const float *, const float *, const int *, const float *, const int *, const float *, float *, const int *);
void ssyrk(const char *, const char *, const int *, const int *, const float *, const float *, const int *, const float *, float *, const int *);
void stbmv(const char *, const char *, const char *, const int *, const int *, const float *, const int *, float *, const int *);
void stbsv(const char *, const char *, const char *, const int *, const int *, const float *, const int *, float *, const int *);
void stpmv(const char *, const char *, const char *, const int *, const float *, float *, const int *);
void stpsv(const char *, const char *, const char *, const int *, const float *, float *, const int *);
void strmm(const char *, const char *, const char *, const char *, const int *, const int *, const float *, const float *, const int *, float *, const int *);
void strmv(const char *, const char *, const char *, const int *, const float *, const int *, float *, const int *);
void strsm(const char *, const char *, const char *, const char *, const int *, const int *, const float *, const float *, const int *, float *, const int *);
void strsv(const char *, const char *, const char *, const int *, const float *, const int *, float *, const int *);
void zaxpy(const int *, const double *, const double *, const int *, double *, const int *);
void zcopy(const int *, const double *, const int *, double *, const int *);
doublec_t zdotc(double *, const int *, const double *, const int *, const double *, const int *);
doublec_t zdotu(double *, const int *, const double *, const int *, const double *, const int *);
void zdscal(const int *, const double *, double *, const int *);
void zgbmv(const char *, const int *, const int *, const int *, const int *, const double *, const double *, const int *, const double *, const int *, const double *, double *, const int *);
void zgemm(const char *, const char *, const int *, const int *, const int *, const double *, const double *, const int *, const double *, const int *, const double *, double *, const int *);
void zgemv(const char *, const int *, const int *, const double *, const double *, const int *, const double *, const int *, const double *, double *, const int *);
void zgerc(const int *, const int *, const double *, const double *, const int *, const double *, const int *, double *, const int *);
void zgeru(const int *, const int *, const double *, const double *, const int *, const double *, const int *, double *, const int *);
void zhbmv(const char *, const int *, const int *, const double *, const double *, const int *, const double *, const int *, const double *, double *, const int *);
void zhemm(const char *, const char *, const int *, const int *, const double *, const double *, const int *, const double *, const int *, const double *, double *, const int *);
void zhemv(const char *, const int *, const double *, const double *, const int *, const double *, const int *, const double *, double *, const int *);
void zher(const char *, const int *, const double *, const double *, const int *, double *, const int *);
void zher2(const char *, const int *, const double *, const double *, const int *, const double *, const int *, double *, const int *);
void zher2k(const char *, const char *, const int *, const int *, const double *, const double *, const int *, const double *, const int *, const double *, double *, const int *);
void zherk(const char *, const char *, const int *, const int *, const double *, const double *, const int *, const double *, double *, const int *);
void zhpmv(const char *, const int *, const double *, const double *, const double *, const int *, const double *, double *, const int *);
void zhpr(const char *, const int *, const double *, const double *, const int *, double *);
void zhpr2(const char *, const int *, const double *, const double *, const int *, const double *, const int *, double *);
void zscal(const int *, const double *, double *, const int *);
void zswap(const int *, double *, const int *, double *, const int *);
void zsymm(const char *, const char *, const int *, const int *, const double *, const double *, const int *, const double *, const int *, const double *, double *, const int *);
void zsyr2k(const char *, const char *, const int *, const int *, const double *, const double *, const int *, const double *, const int *, const double *, double *, const int *);
void zsyrk(const char *, const char *, const int *, const int *, const double *, const double *, const int *, const double *, double *, const int *);
void ztbmv(const char *, const char *, const char *, const int *, const int *, const double *, const int *, double *, const int *);
void ztbsv(const char *, const char *, const char *, const int *, const int *, const double *, const int *, double *, const int *);
void ztpmv(const char *, const char *, const char *, const int *, const double *, double *, const int *);
void ztpsv(const char *, const char *, const char *, const int *, const double *, double *, const int *);
void ztrmm(const char *, const char *, const char *, const char *, const int *, const int *, const double *, const double *, const int *, double *, const int *);
void ztrmv(const char *, const char *, const char *, const int *, const double *, const int *, double *, const int *);
void ztrsm(const char *, const char *, const char *, const char *, const int *, const int *, const double *, const double *, const int *, double *, const int *);
void ztrsv(const char *, const char *, const char *, const int *, const double *, const int *, double *, const int *);
#endif /* BLAS_H */
