#ifndef BLAS_H
#define BLAS_H
typedef struct {
    float r, i;
} floatc_t;
typedef struct {
    double r, i;
} doublec_t;
void caxpy_(const int *, const float *, const float *, const int *, float *, const int *);
void ccopy_(const int *, const float *, const int *, float *, const int *);
floatc_t cdotc_(const int *, const float *, const int *, const float *, const int *);
floatc_t cdotu_(const int *, const float *, const int *, const float *, const int *);
void cgbmv_(const char *, const int *, const int *, const int *, const int *, const float *, const float *, const int *, const float *, const int *, const float *, float *, const int *);
void cgemm_(const char *, const char *, const int *, const int *, const int *, const float *, const float *, const int *, const float *, const int *, const float *, float *, const int *);
void cgemv_(const char *, const int *, const int *, const float *, const float *, const int *, const float *, const int *, const float *, float *, const int *);
void cgerc_(const int *, const int *, const float *, const float *, const int *, const float *, const int *, float *, const int *);
void cgeru_(const int *, const int *, const float *, const float *, const int *, const float *, const int *, float *, const int *);
void chbmv_(const char *, const int *, const int *, const float *, const float *, const int *, const float *, const int *, const float *, float *, const int *);
void chemm_(const char *, const char *, const int *, const int *, const float *, const float *, const int *, const float *, const int *, const float *, float *, const int *);
void chemv_(const char *, const int *, const float *, const float *, const int *, const float *, const int *, const float *, float *, const int *);
void cher_(const char *, const int *, const float *, const float *, const int *, float *, const int *);
void cher2_(const char *, const int *, const float *, const float *, const int *, const float *, const int *, float *, const int *);
void cher2k_(const char *, const char *, const int *, const int *, const float *, const float *, const int *, const float *, const int *, const float *, float *, const int *);
void cherk_(const char *, const char *, const int *, const int *, const float *, const float *, const int *, const float *, float *, const int *);
void chpmv_(const char *, const int *, const float *, const float *, const float *, const int *, const float *, float *, const int *);
void chpr_(const char *, const int *, const float *, const float *, const int *, float *);
void chpr2_(const char *, const int *, const float *, const float *, const int *, const float *, const int *, float *);
void cscal_(const int *, const float *, float *, const int *);
void csscal_(const int *, const float *, float *, const int *);
void cswap_(const int *, float *, const int *, float *, const int *);
void csymm_(const char *, const char *, const int *, const int *, const float *, const float *, const int *, const float *, const int *, const float *, float *, const int *);
void csyr2k_(const char *, const char *, const int *, const int *, const float *, const float *, const int *, const float *, const int *, const float *, float *, const int *);
void csyrk_(const char *, const char *, const int *, const int *, const float *, const float *, const int *, const float *, float *, const int *);
void ctbmv_(const char *, const char *, const char *, const int *, const int *, const float *, const int *, float *, const int *);
void ctbsv_(const char *, const char *, const char *, const int *, const int *, const float *, const int *, float *, const int *);
void ctpmv_(const char *, const char *, const char *, const int *, const float *, float *, const int *);
void ctpsv_(const char *, const char *, const char *, const int *, const float *, float *, const int *);
void ctrmm_(const char *, const char *, const char *, const char *, const int *, const int *, const float *, const float *, const int *, float *, const int *);
void ctrmv_(const char *, const char *, const char *, const int *, const float *, const int *, float *, const int *);
void ctrsm_(const char *, const char *, const char *, const char *, const int *, const int *, const float *, const float *, const int *, float *, const int *);
void ctrsv_(const char *, const char *, const char *, const int *, const float *, const int *, float *, const int *);
double dasum_(const int *, const double *, const int *);
void daxpy_(const int *, const double *, const double *, const int *, double *, const int *);
void dcopy_(const int *, const double *, const int *, double *, const int *);
double ddot_(const int *, const double *, const int *, const double *, const int *);
void dgbmv_(const char *, const int *, const int *, const int *, const int *, const double *, const double *, const int *, const double *, const int *, const double *, double *, const int *);
void dgemm_(const char *, const char *, const int *, const int *, const int *, const double *, const double *, const int *, const double *, const int *, const double *, double *, const int *);
void dgemv_(const char *, const int *, const int *, const double *, const double *, const int *, const double *, const int *, const double *, double *, const int *);
void dger_(const int *, const int *, const double *, const double *, const int *, const double *, const int *, double *, const int *);
double dnrm2_(const int *, const double *, const int *);
void drot_(const int *, double *, const int *, double *, const int *, const double *, const double *);
void drotg_(double *, double *, double *, double *);
void drotm_(const int *, double *, const int *, double *, const int *, const double *);
void drotmg_(double *, double *, double *, const double *, double *);
void dsbmv_(const char *, const int *, const int *, const double *, const double *, const int *, const double *, const int *, const double *, double *, const int *);
void dscal_(const int *, const double *, double *, const int *);
double dsdot_(const int *, const float *, const int *, const float *, const int *);
void dspmv_(const char *, const int *, const double *, const double *, const double *, const int *, const double *, double *, const int *);
void dspr_(const char *, const int *, const double *, const double *, const int *, double *);
void dspr2_(const char *, const int *, const double *, const double *, const int *, const double *, const int *, double *);
void dswap_(const int *, double *, const int *, double *, const int *);
void dsymm_(const char *, const char *, const int *, const int *, const double *, const double *, const int *, const double *, const int *, const double *, double *, const int *);
void dsymv_(const char *, const int *, const double *, const double *, const int *, const double *, const int *, const double *, double *, const int *);
void dsyr_(const char *, const int *, const double *, const double *, const int *, double *, const int *);
void dsyr2_(const char *, const int *, const double *, const double *, const int *, const double *, const int *, double *, const int *);
void dsyr2k_(const char *, const char *, const int *, const int *, const double *, const double *, const int *, const double *, const int *, const double *, double *, const int *);
void dsyrk_(const char *, const char *, const int *, const int *, const double *, const double *, const int *, const double *, double *, const int *);
void dtbmv_(const char *, const char *, const char *, const int *, const int *, const double *, const int *, double *, const int *);
void dtbsv_(const char *, const char *, const char *, const int *, const int *, const double *, const int *, double *, const int *);
void dtpmv_(const char *, const char *, const char *, const int *, const double *, double *, const int *);
void dtpsv_(const char *, const char *, const char *, const int *, const double *, double *, const int *);
void dtrmm_(const char *, const char *, const char *, const char *, const int *, const int *, const double *, const double *, const int *, double *, const int *);
void dtrmv_(const char *, const char *, const char *, const int *, const double *, const int *, double *, const int *);
void dtrsm_(const char *, const char *, const char *, const char *, const int *, const int *, const double *, const double *, const int *, double *, const int *);
void dtrsv_(const char *, const char *, const char *, const int *, const double *, const int *, double *, const int *);
double dzasum_(const int *, const double *, const int *);
double dznrm2_(const int *, const double *, const int *);
int icamax_(const int *, const float *, const int *);
int idamax_(const int *, const double *, const int *);
int isamax_(const int *, const float *, const int *);
int izamax_(const int *, const double *, const int *);
float sasum_(const int *, const float *, const int *);
void saxpy_(const int *, const float *, const float *, const int *, float *, const int *);
float scasum_(const int *, const float *, const int *);
float scnrm2_(const int *, const float *, const int *);
void scopy_(const int *, const float *, const int *, float *, const int *);
float sdot_(const int *, const float *, const int *, const float *, const int *);
float sdsdot_(const int *, const float *, const float *, const int *, const float *, const int *);
void sgbmv_(const char *, const int *, const int *, const int *, const int *, const float *, const float *, const int *, const float *, const int *, const float *, float *, const int *);
void sgemm_(const char *, const char *, const int *, const int *, const int *, const float *, const float *, const int *, const float *, const int *, const float *, float *, const int *);
void sgemv_(const char *, const int *, const int *, const float *, const float *, const int *, const float *, const int *, const float *, float *, const int *);
void sger_(const int *, const int *, const float *, const float *, const int *, const float *, const int *, float *, const int *);
float snrm2_(const int *, const float *, const int *);
void srot_(const int *, float *, const int *, float *, const int *, const float *, const float *);
void srotg_(float *,float *,float *,float *);
void srotm_(const int *, float *, const int *, float *, const int *, const float *);
void srotmg_(float *, float *, float *, const float *, float *);
void ssbmv_(const char *, const int *, const int *, const float *, const float *, const int *, const float *, const int *, const float *, float *, const int *);
void sscal_(const int *, const float *, float *, const int *);
void sspmv_(const char *, const int *, const float *, const float *, const float *, const int *, const float *, float *, const int *);
void sspr_(const char *, const int *, const float *, const float *, const int *, float *);
void sspr2_(const char *, const int *, const float *, const float *, const int *, const float *, const int *, float *);
void sswap_(const int *, float *, const int *, float *, const int *);
void ssymm_(const char *, const char *, const int *, const int *, const float *, const float *, const int *, const float *, const int *, const float *, float *, const int *);
void ssymv_(const char *, const int *, const float *, const float *, const int *, const float *, const int *, const float *, float *, const int *);
void ssyr_(const char *, const int *, const float *, const float *, const int *, float *, const int *);
void ssyr2_(const char *, const int *, const float *, const float *, const int *, const float *, const int *, float *, const int *);
void ssyr2k_(const char *, const char *, const int *, const int *, const float *, const float *, const int *, const float *, const int *, const float *, float *, const int *);
void ssyrk_(const char *, const char *, const int *, const int *, const float *, const float *, const int *, const float *, float *, const int *);
void stbmv_(const char *, const char *, const char *, const int *, const int *, const float *, const int *, float *, const int *);
void stbsv_(const char *, const char *, const char *, const int *, const int *, const float *, const int *, float *, const int *);
void stpmv_(const char *, const char *, const char *, const int *, const float *, float *, const int *);
void stpsv_(const char *, const char *, const char *, const int *, const float *, float *, const int *);
void strmm_(const char *, const char *, const char *, const char *, const int *, const int *, const float *, const float *, const int *, float *, const int *);
void strmv_(const char *, const char *, const char *, const int *, const float *, const int *, float *, const int *);
void strsm_(const char *, const char *, const char *, const char *, const int *, const int *, const float *, const float *, const int *, float *, const int *);
void strsv_(const char *, const char *, const char *, const int *, const float *, const int *, float *, const int *);
void zaxpy_(const int *, const double *, const double *, const int *, double *, const int *);
void zcopy_(const int *, const double *, const int *, double *, const int *);
doublec_t zdotc_(const int *, const double *, const int *, const double *, const int *);
doublec_t zdotu_(const int *, const double *, const int *, const double *, const int *);
void zdscal_(const int *, const double *, double *, const int *);
void zgbmv_(const char *, const int *, const int *, const int *, const int *, const double *, const double *, const int *, const double *, const int *, const double *, double *, const int *);
void zgemm_(const char *, const char *, const int *, const int *, const int *, const double *, const double *, const int *, const double *, const int *, const double *, double *, const int *);
void zgemv_(const char *, const int *, const int *, const double *, const double *, const int *, const double *, const int *, const double *, double *, const int *);
void zgerc_(const int *, const int *, const double *, const double *, const int *, const double *, const int *, double *, const int *);
void zgeru_(const int *, const int *, const double *, const double *, const int *, const double *, const int *, double *, const int *);
void zhbmv_(const char *, const int *, const int *, const double *, const double *, const int *, const double *, const int *, const double *, double *, const int *);
void zhemm_(const char *, const char *, const int *, const int *, const double *, const double *, const int *, const double *, const int *, const double *, double *, const int *);
void zhemv_(const char *, const int *, const double *, const double *, const int *, const double *, const int *, const double *, double *, const int *);
void zher_(const char *, const int *, const double *, const double *, const int *, double *, const int *);
void zher2_(const char *, const int *, const double *, const double *, const int *, const double *, const int *, double *, const int *);
void zher2k_(const char *, const char *, const int *, const int *, const double *, const double *, const int *, const double *, const int *, const double *, double *, const int *);
void zherk_(const char *, const char *, const int *, const int *, const double *, const double *, const int *, const double *, double *, const int *);
void zhpmv_(const char *, const int *, const double *, const double *, const double *, const int *, const double *, double *, const int *);
void zhpr_(const char *, const int *, const double *, const double *, const int *, double *);
void zhpr2_(const char *, const int *, const double *, const double *, const int *, const double *, const int *, double *);
void zscal_(const int *, const double *, double *, const int *);
void zswap_(const int *, double *, const int *, double *, const int *);
void zsymm_(const char *, const char *, const int *, const int *, const double *, const double *, const int *, const double *, const int *, const double *, double *, const int *);
void zsyr2k_(const char *, const char *, const int *, const int *, const double *, const double *, const int *, const double *, const int *, const double *, double *, const int *);
void zsyrk_(const char *, const char *, const int *, const int *, const double *, const double *, const int *, const double *, double *, const int *);
void ztbmv_(const char *, const char *, const char *, const int *, const int *, const double *, const int *, double *, const int *);
void ztbsv_(const char *, const char *, const char *, const int *, const int *, const double *, const int *, double *, const int *);
void ztpmv_(const char *, const char *, const char *, const int *, const double *, double *, const int *);
void ztpsv_(const char *, const char *, const char *, const int *, const double *, double *, const int *);
void ztrmm_(const char *, const char *, const char *, const char *, const int *, const int *, const double *, const double *, const int *, double *, const int *);
void ztrmv_(const char *, const char *, const char *, const int *, const double *, const int *, double *, const int *);
void ztrsm_(const char *, const char *, const char *, const char *, const int *, const int *, const double *, const double *, const int *, double *, const int *);
void ztrsv_(const char *, const char *, const char *, const int *, const double *, const int *, double *, const int *);
#endif /* BLAS_H */
